INSERT INTO engineers (user_id, name, specialization, experience, bio) VALUES
(2, 'John Smith', 'Civil', '5 years', 'Expert in civil engineering projects.'),
(3, 'Sarah Johnson', 'Mechanical', '4 years', 'Mechanical systems specialist.'),
(4, 'Michael Brown', 'Electrical', '6 years', 'Electrical design and implementation.'),
(5, 'Emily Davis', 'Software', '3 years', 'Full-stack software engineer.'),
(6, 'James Wilson', 'Structural', '7 years', 'Structural analysis and design.'),
(7, 'Lisa Anderson', 'Chemical', '5 years', 'Chemical process engineer.'),
(8, 'Robert Taylor', 'Aerospace', '8 years', 'Aerospace systems expert.'),
(9, 'Jennifer White', 'Biomedical', '2 years', 'Biomedical device developer.'),
(10, 'David Miller', 'Industrial', '6 years', 'Industrial process optimization.'),
(11, 'Patricia Moore', 'Petroleum', '9 years', 'Petroleum extraction specialist.'),
(12, 'Charles Jackson', 'Computer', '4 years', 'Computer hardware engineer.'),
(13, 'Karen Martin', 'Nuclear', '10 years', 'Nuclear systems engineer.'),
(14, 'Thomas Harris', 'Marine', '5 years', 'Marine engineering projects.'),
(15, 'Sandra Clark', 'Systems', '6 years', 'Systems integration expert.'),
(16, 'Christopher Lewis', 'Automotive', '3 years', 'Automotive design engineer.'),
(17, 'Nancy Lee', 'Agricultural', '7 years', 'Agricultural machinery specialist.'),
(18, 'Daniel Walker', 'Materials', '4 years', 'Materials science engineer.'),
(19, 'Betty Hall', 'Robotics', '5 years', 'Robotics and automation.'),
(20, 'Matthew Young', 'Geotechnical', '8 years', 'Geotechnical analysis.'),
(21, 'Sandra Hernandez', 'Telecommunications', '6 years', 'Telecom systems engineer.'),
(22, 'Mark Green', 'Mining', '9 years', 'Mining operations expert.'),
(23, 'Angela Adams', 'Energy', '7 years', 'Renewable energy engineer.'),
(24, 'Donald Nelson', 'Mechatronics', '3 years', 'Mechatronics systems.'),
(25, 'Margaret Carter', 'Data', '2 years', 'Data engineering and analytics.'),
(26, 'Steven Mitchell', 'Civil', '8 years', 'Civil infrastructure specialist with 20+ major projects.'),
(27, 'Jessica Thompson', 'Mechanical', '6 years', 'Advanced mechanical design and CAD expertise.'),
(28, 'Ryan Anderson', 'Electrical', '7 years', 'Electrical systems and power distribution expert.'),
(29, 'Megan Taylor', 'Software', '5 years', 'Backend and database architecture specialist.'),
(30, 'Andrew Jackson', 'Structural', '9 years', 'Structural design with focus on seismic analysis.'),
(31, 'Lauren Martin', 'Chemical', '6 years', 'Specialized in petrochemical processes.'),
(32, 'Kevin White', 'Aerospace', '10 years', 'Aircraft design and aerodynamics expert.'),
(33, 'Rebecca Davis', 'Biomedical', '4 years', 'Medical device innovation specialist.'),
(34, 'Justin Garcia', 'Industrial', '7 years', 'Manufacturing optimization expert.'),
(35, 'Stephanie Rodriguez', 'Petroleum', '11 years', 'Oil and gas extraction pioneer.'),
(36, 'Brandon Clark', 'Computer', '5 years', 'Computer architecture and chip design.'),
(37, 'Heather Martinez', 'Nuclear', '12 years', 'Nuclear safety and regulatory expert.'),
(38, 'Eric Lewis', 'Marine', '6 years', 'Offshore structure design specialist.'),
(39, 'Victoria Scott', 'Systems', '8 years', 'Large-scale system integration expert.'),
(40, 'Jonathan Green', 'Automotive', '5 years', 'Electric vehicle technology pioneer.'),
(41, 'Michelle Adams', 'Agricultural', '8 years', 'Sustainable farming technology expert.'),
(42, 'Aaron Nelson', 'Materials', '6 years', 'Advanced materials and composites specialist.'),
(43, 'Nicole Carter', 'Robotics', '7 years', 'Autonomous systems and AI robotics expert.'),
(44, 'Kyle Rivera', 'Geotechnical', '9 years', 'Foundation design and soil analysis expert.'),
(45, 'Hannah Brooks', 'Telecommunications', '7 years', '5G and network infrastructure specialist.'),
(46, 'Brian Phillips', 'Mining', '10 years', 'Mine planning and operational efficiency expert.'),
(47, 'Alicia Campbell', 'Energy', '8 years', 'Solar and wind energy systems expert.'),
(48, 'Gregory Parker', 'Mechatronics', '5 years', 'Robotics and control systems specialist.'),
(49, 'Danielle Edwards', 'Data', '4 years', 'Big data analytics and machine learning expert.'),
(50, 'Samuel Murphy', 'Software', '8 years', 'Cloud infrastructure and DevOps expert.');

